### PR TITLE
Updates to appease the BBC so the site can be referenced.

### PR DESCRIPTION
**Pull request by ntoll**
For the BBC to be able to reference this website they've told me we need to link to the "official" editor. This PR includes this information and also corrects muPython -> MicroPython. It's always MicroPython... ;-)

If this can be checked/merged quickly then I can prod the right person at the BBC. :-)

### CODE REVIEW

**Comment by jezdean** [comment]
Hi Nick,

I've made a few changes to your PR. I did `git push -u origin pr/5` but I'm not sure where it went. Can you see it?

 Can you let me know your thoughts. More than happy to change it.

**Comment by ntoll** [comment]
If I were you, I'd merge my pull request and then update on your master.

**Comment by jezdean** [comment]
I did this to work on your changes:

```
git checkout -b ntoll-master master
git pull https://github.com/ntoll/microbit-playground.github.io.git master
```

In my project directory.

I cut and pasted it from 'Merging Via Command Line' below the pull request.

I kept all your changes except  the index page. I split the text into two columns so it'd be clearer.

microbit-playground

I did a screenshot!

**Comment by ntoll** [comment]
Great stuff. If you put the min-height attribute as the same on both columns they'll line up. ;-)

When you're happy just keep following the instructions from GitHub.

**Comment by jezdean** [comment]
Found it! It's in the repository on the [pr/5 branch](https://github.com/microbit-playground/microbit-playground.github.io/tree/pr/5)

**Comment by jezdean** [comment]
2016-03-18 20_36_29-micro_bit playground

That's the finished article.

Changes:
- Made it responsive (now looks good on a phone)
- I've made mu into Mu. I thought the lower case made it look less clickable.
- Changed 'download' to _download_
- Styled out the distracting links for visit and download; the call to action is clear.
- Micro:bit to micro:bit
- Each column same height

I'm not too fussed about the BBC liking/linking it (BBC Legal is different!). It's more about clear about what Playground is for. Now mu has an excellent website it feels a bit pointless. I want to move towards more of a resource for teachers and write ups of more ~~games~~ programs. I'm working on a [3D model of the micro:bit ](https://sketchfab.com/models/ccf2a7605a4a4ff783ffa5f86f1fac5d) and other clip art. (this would be much easier with design files, BBC). The cheat sheet would be for anyone. I kinda wish I'd done that one first.

Anyway. Back on topic. I'm really happy with it. If you're happy, I'm happy!

What do I do with this pull request?

**Comment by ntoll** [comment]
You merge it! ;-)

**Comment by jezdean** [comment]
This pull request is the old new one. The branch I did the changes on is pr/5 in my repository. Do I merge this one and then the other one? Or do I merge the pr/5 in my repository only?

**Comment by ntoll** [comment]
Only merge the one you've subsequently made changes to. :-)

**Comment by jezdean** [comment]
Cross your fingers.

**Comment by ntoll** [comment]
It should just be, on your master branch: `git merge pr/5` then `git push` it all to GitHub :-)

**Comment by ntoll** [comment]
Also, where's the cheatsheet code hosted? :-)

**Comment by jezdean** [comment]
It's on Gitlab. You can't have an ANAME and CNAME on github. I need your advice on the cheat sheet; I'll drop you an email. Thanks for your help.

**Pull request merged**
